#配置SSL
server:
  port: 8082
  servlet:
    #context-path: /zysz
    multipart:
    enabled: true
    max-file-size:
    max-request-size: -1
spring:
  task:
    execution:
      pool:
        core-size: 5        # 核心线程数
        max-size: 10        # 最大线程数
        queue-capacity: 100 # 任务队列容量
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 设置总上传的文件大小
      max-request-size: 2000MB
  datasource:
    #mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/5619?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      max-total: 150
      max-idle: 10
  mail:
    host: smtp.gmail.com
    port: 587
    username: yyfnhk@gmail.com
    password: mqxbbhdchlgbaxlb
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
Paypal:
    mode: sandbox
    client:
      app: AVBtfivPRGQ2j7rM88EbwrmZCcNfmStsoutgEXy0yWZCL9dyflXl8ejXfLfu97GDbWZougbv8tPJhpbP
      secret: ED2yTrWDFro3Y_4FrU0XNk524jOjmXKajTxxmoA20CIb5HtR9zb3Rf7urkipd62RbptrrTm19v8IfQEh