#配置SSL
server:
  port: 8082
  servlet:
    #context-path: /zysz
    multipart:
    enabled: true
    max-file-size:
    max-request-size: -1
spring:
  task:
    execution:
      pool:
        core-size: 5        # 核心线程数
        max-size: 10        # 最大线程数
        queue-capacity: 100 # 任务队列容量
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 设置总上传的文件大小
      max-request-size: 2000MB
  datasource:
    #mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/evangelion?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
    dbcp2:
      max-total: 150
      max-idle: 10
  mail:
    host: smtp.qq.com
    port: 587
     #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    username: 294006654@qq.com
    password: sfnqzdzjtbolbhch
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
Paypal:
    mode: sandbox
    client:
      app: Adk-ElqgP7foct2vVjDYMTn3k2MvctXLm-4mltFIeTrLF4l-er9LwLCY3fWrLe6FLlwq4jBVhlckayMa
      secret: EMkndKRL0_QbPdYbFSYj0tDac3ld_SM3E9JJeS4tYd4WecVtCA86wwT2hFSSOzh59D26pIQKSjMzDuQ2